#!/bin/bash
read -p "Please enter a path name: " pathName
if test -z "${pathName}"
then
	oldestFileInTheCurDir=`find $PWD -printf '%T+ %p\n' | sort | head -n 1`
	read -p "$oldestFileInTheCurDir is the oldest file in your current working directory. Do you want to delete it?: " answer
	case $answer in

		[yY] | [yY][eE][sS] )

			rm $oldestFileInTheCurDir
			;;

		[nN] | [nN][oO] )

			echo "You did not delete the file."
			;;
		*)
			echo "Invalid Input";
			exit 1
			;;
	esac

	
else
	if [ ! -d "${pathName}" ]
	then 
		echo "THIS PATH IS NOT VALID!"
	else
		oldestFileInThePath=`find ${pathName} -printf '%T+ %p\n' | sort | head -n 1`
		read -p "Do you want to delete the oldest file in this directory?: " answer1
		case $answer1 in

			[yY] | [yY][eE][sS] )

				rm $oldestFileInThePath
				;;

			[nN] | [nN][oO] )

				echo "You did not delete the file."
				;;
			*)
				echo "Invalid Input";
				exit 1
				;;
		esac
	fi
fi

